#!/bin/bash

function check_ssl
{
if true | openssl s_client -connect $p:443 2>/dev/null | openssl x509 -noout -checkend 0 2>/dev/null; then
  :
else
  echo $p "Certificate is expired"
  exit 127
fi
}

filename='domains'
while read p; do
 check_ssl | grep expired
done < $filename

