#!/bin/bash

function check_ssl
{
if true | openssl s_client -connect $p:443 2>/dev/null | openssl x509 -noout -checkend 0 2>/dev/null; then
:
else
  echo $p "has expired certificate"
fi
}

filename="$1"
while read p; do
  check_ssl | grep expired
done < $filename
